#Lab 05 - Lists & For Loops Problem 3 - Range function and For loop
#Heather Gates

#(a) Use Range function, save to list, and display results
seq1 = range(5,25,4)
list1 = list(seq1)
print('Integers generated by range(5,25,4):', list1)
#(b) for loop to display results on separate lines
for element in seq1:
    print(element)

#(c) Use Range function, save to list, display results
seq2 = range(26,-2,-7)
list2 = list(seq2)
print('Integers generated by rang(26,-2,-7):', list2)
for element in seq2:
    print(element)
#(d) Use for loop to calculate total of elements. Display total.
print('Total of integers in range(26,-2,-7):')
total = 0
for element in seq2:
    total = total + element
print(total)
